name: Deploy to Windows VM

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -o ./publish

    - name: Copy files to Windows VM using SCP
      shell: pwsh
      run: |
        $sourcePath = "./publish/*"
        $destinationPath = "C:/inetpub/wwwroot/LibraryApp"
        $host = "${{ secrets.AZURE_VM_IP }}"
        $username = "${{ secrets.AZURE_VM_USER }}"
        $privateKey = "${{ secrets.AZURE_VM_PRIVATE_KEY }}"
        $port = 22

        # Create an SSH session
        $session = New-PSSession -HostName $host -UserName $username -KeyFile $privateKey -Port $port

        # Copy files using SCP
        Copy-Item -ToSession $session -Path $sourcePath -Destination $destinationPath -Recurse

    - name: Restart IIS
      shell: pwsh
      run: |
        $host = "${{ secrets.AZURE_VM_IP }}"
        $username = "${{ secrets.AZURE_VM_USER }}"
        $privateKey = "${{ secrets.AZURE_VM_PRIVATE_KEY }}"
        $port = 22

        # Restart IIS using SSH
        ssh -i $privateKey -p $port $username@$host "iisreset"
